server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YasserTahri/spring-cloud-config
          search-paths:
            - microservice*
          delete-untracked-branches: true
          defaultLabel: master

